2018-11-25 16:01:03 ERROR (Thread-2) [homeassistant.util.yaml] YAML file /home/pi/.homeassistant/configuration.yaml contains duplicate key "group". Check lines 79 and 85.
2018-11-25 16:01:03 ERROR (Thread-2) [homeassistant.util.yaml] YAML file /home/pi/.homeassistant/configuration.yaml contains duplicate key "homeassistant". Check lines 0 and 102.
2018-11-25 16:01:03 ERROR (Thread-2) [homeassistant.util.yaml] YAML file /home/pi/.homeassistant/configuration.yaml contains duplicate key "sensor". Check lines 55 and 108.
2018-11-25 16:01:03 ERROR (Thread-2) [homeassistant.util.yaml] YAML file /home/pi/.homeassistant/configuration.yaml contains duplicate key "script". Check lines 81 and 163.
2018-11-25 16:01:03 ERROR (Thread-2) [homeassistant.util.yaml] YAML file /home/pi/.homeassistant/configuration.yaml contains duplicate key "automation". Check lines 80 and 194.
2018-11-25 16:01:05 WARNING (MainThread) [homeassistant.config] Incomplete core configuration. Auto detected latitude: None, longitude: None, name: None, time_zone: None
2018-11-25 16:01:13 ERROR (MainThread) [homeassistant.setup] Error during setup of component sun
Traceback (most recent call last):
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 142, in _async_setup_component
    result = await component.async_setup(hass, processed_config)
  File "/usr/local/lib/python3.5/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/components/sun.py", line 47, in async_setup
    sun = Sun(hass, get_astral_location(hass))
  File "/home/pi/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/sun.py", line 19, in get_astral_location
    timezone = hass.config.time_zone.zone
AttributeError: 'NoneType' object has no attribute 'zone'
